---
- name: restart mesos slaves
  service:
     name: mesos-slave
     state: restarted
     enabled: yes
  when: inventory_hostname in groups['mesos-slaves']


- name: reload resolvconf
  command: resolvconf -u
